import { Plane, Clock, MapPin, Calendar } from "lucide-react";

export default function About() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6 text-center">About FlightBack</h1>
      
      <div className="max-w-3xl mx-auto bg-card rounded-lg shadow-lg p-6 mb-8">
        <h2 className="text-2xl font-semibold mb-4 flex items-center">
          <Plane className="mr-2 text-primary" /> Our Mission
        </h2>
        <p className="text-muted-foreground mb-6">
          FlightBack was created to provide a simple and intuitive way to generate custom flight tickets for
          demonstration purposes. Whether you need a prop for a presentation, a visual aid for a project,
          or just want to explore what-if travel scenarios, our ticket generator has you covered.
        </p>
        
        <h2 className="text-2xl font-semibold mb-4 flex items-center">
          <Clock className="mr-2 text-primary" /> How It Works
        </h2>
        <p className="text-muted-foreground mb-4">
          Our application uses real-world airport data and calculates realistic flight times based on
          geographical coordinates. The Haversine formula is applied to determine the great-circle distance
          between airports, accounting for the Earth's curvature.
        </p>
        <p className="text-muted-foreground mb-6">
          Once you select your origin and destination, we calculate:
        </p>
        <ul className="list-disc pl-6 mb-6 text-muted-foreground">
          <li>Accurate flight duration based on distance</li>
          <li>Local departure and arrival times with timezone differences</li>
          <li>Boarding times and gate information</li>
          <li>A unique booking reference for each ticket</li>
        </ul>
        
        <h2 className="text-2xl font-semibold mb-4 flex items-center">
          <MapPin className="mr-2 text-primary" /> Global Coverage
        </h2>
        <p className="text-muted-foreground mb-6">
          FlightBack includes airports and airlines from all major regions of the world:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
          <div className="bg-background rounded p-3">
            <h3 className="font-medium mb-2">Regions</h3>
            <ul className="list-disc pl-6 text-muted-foreground text-sm">
              <li>North America</li>
              <li>Europe</li>
              <li>Asia</li>
              <li>Oceania</li>
              <li>Africa</li>
              <li>South America</li>
            </ul>
          </div>
          <div className="bg-background rounded p-3">
            <h3 className="font-medium mb-2">Features</h3>
            <ul className="list-disc pl-6 text-muted-foreground text-sm">
              <li>Multiple airlines per route</li>
              <li>PDF ticket generation</li>
              <li>Mobile-friendly design</li>
              <li>Hierarchical airport selection</li>
              <li>24-hour time format</li>
            </ul>
          </div>
        </div>
        
        <h2 className="text-2xl font-semibold mb-4 flex items-center">
          <Calendar className="mr-2 text-primary" /> Disclaimer
        </h2>
        <p className="text-muted-foreground">
          The tickets generated by FlightBack are for demonstration purposes only and do not represent
          actual flight bookings. Airline logos and names are used for illustrative purposes.
          FlightBack is not affiliated with any commercial airline or booking service.
        </p>
      </div>
    </div>
  );
}