import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { HelpCircle, Search, Plane, Ticket, Mail, Users } from "lucide-react";

export default function Help() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex items-center justify-center mb-6">
        <HelpCircle className="text-primary mr-2 h-6 w-6" />
        <h1 className="text-3xl font-bold text-center">Help Center</h1>
      </div>

      <div className="max-w-3xl mx-auto mb-8">
        <Card>
          <CardHeader>
            <CardTitle>How to Use FlightBack</CardTitle>
            <CardDescription>
              Follow this step-by-step guide to generate your custom flight ticket
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-start">
                <div className="bg-primary/10 p-3 rounded-full mr-4">
                  <Search className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium">1. Select Your Flight</h3>
                  <p className="text-muted-foreground text-sm">
                    Choose your departure and arrival airports, date, and time. Our system will
                    calculate the flight duration and arrival time automatically.
                  </p>
                </div>
              </div>
              
              <div className="flex items-start">
                <div className="bg-primary/10 p-3 rounded-full mr-4">
                  <Plane className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium">2. Choose an Airline</h3>
                  <p className="text-muted-foreground text-sm">
                    Browse through available airlines for your selected route. Each airline offers
                    different flight times and pricing options.
                  </p>
                </div>
              </div>
              
              <div className="flex items-start">
                <div className="bg-primary/10 p-3 rounded-full mr-4">
                  <Users className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium">3. Enter Passenger Details</h3>
                  <p className="text-muted-foreground text-sm">
                    Fill in the passenger information for the ticket. All fields are required
                    for generating a complete ticket.
                  </p>
                </div>
              </div>
              
              <div className="flex items-start">
                <div className="bg-primary/10 p-3 rounded-full mr-4">
                  <Ticket className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium">4. Review and Generate</h3>
                  <p className="text-muted-foreground text-sm">
                    Preview your ticket details before generation. Make sure all information
                    is correct as it will appear on your final ticket.
                  </p>
                </div>
              </div>
              
              <div className="flex items-start">
                <div className="bg-primary/10 p-3 rounded-full mr-4">
                  <Mail className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium">5. Download or Email</h3>
                  <p className="text-muted-foreground text-sm">
                    Once generated, you can download your ticket as a PDF or send it to your
                    email for convenient access.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="max-w-3xl mx-auto">
        <h2 className="text-2xl font-semibold mb-4">Frequently Asked Questions</h2>
        
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger>Are these real flight tickets?</AccordionTrigger>
            <AccordionContent>
              No, the tickets generated by FlightBack are for demonstration purposes only.
              They cannot be used for actual travel and do not represent real bookings with any airline.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-2">
            <AccordionTrigger>How accurate are the flight times?</AccordionTrigger>
            <AccordionContent>
              Our flight times are calculated using the Haversine formula based on actual
              airport coordinates. While they represent reasonable estimates, they don't account
              for factors like weather, aircraft type, or specific airline routes.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-3">
            <AccordionTrigger>Can I edit a ticket after it's generated?</AccordionTrigger>
            <AccordionContent>
              Once a ticket is generated, you cannot edit it directly. If you need to make changes,
              you'll need to generate a new ticket with the corrected information.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-4">
            <AccordionTrigger>Why can't I find a specific airport?</AccordionTrigger>
            <AccordionContent>
              While we include major airports from around the world, our database may not contain
              every airport. We regularly update our database to add more airports and airlines.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-5">
            <AccordionTrigger>Is my data saved or shared?</AccordionTrigger>
            <AccordionContent>
              The passenger information you enter is only used to generate your flight ticket.
              We don't save or share your personal data with any third parties.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}